name: Build Application

runs:

  using: composite

  steps:
  - name: Checkout repository
    #run: git clone https://github.com/abhipreets2/apartment-renter.git .
    uses: actions/checkout@v4

  - name: Set up python
    uses: actions/setup-python@v5
    with:
      python-version: '3.10'

  - name: Install poetry
    uses: snok/install-poetry@v1
    with:
      virtualenvs-in-project: true

  - name: Load cached venv
    uses: actions/cache@v4
    id: cached-poetry-dependencies
    with:
      path: .venv
      key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}

  - name: Install dependencies using poetry
    if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
    run: poetry run make install
